Repository i-on-project/integration, pull requests merged in 2020-04, with the labels that each got.

#14 Updated gradlew execution flag
  gradlew
Labels: bug

#17 Missing CODEOWNERS
  .github/CODEOWNERS
Labels: bug

#18 Added ISEL timetable extraction job specification
  docs/.gitkeep
  docs/batch jobs/isel-timetable-batch-specification.md
Labels: documentation

#20 Corrected teaching "body" to teaching staff in timetable batch specification document
  docs/batch jobs/isel-timetable-batch-specification.md
Labels: documentation

#15 Added Dockerfile, .dockerignore
  .dockerignore
  Dockerfile
  build.gradle.kts
Labels: enhancement

#26 Ignore idea folder. Added .gitattributes
  .gitattributes
  .gitignore
Labels: bug

#27 Configure workflow
  .dockerignore
  .github/workflows/IOnIntegration_PR.yml
  .github/workflows/IOnIntegration_Production.yml
  .github/workflows/IOnIntegration_Staging.yml
  Dockerfile
  build.gradle.kts
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
  src/test/kotlin/org/ionproject/integration/IOnIntegrationApplicationTests.kt
Labels: enhancement

#49 Fixed incorrect git ref for tag
  build.gradle.kts
Labels: bug

#50 Create project base structure; Add postgres dependency
  build.gradle.kts
  libs/.gitkeep
  src/main/kotlin/org/ionproject/integration/extractor/.gitkeep
  src/main/kotlin/org/ionproject/integration/file/.gitkeep
  src/main/kotlin/org/ionproject/integration/format/.gitkeep
  src/main/kotlin/org/ionproject/integration/hash/.gitkeep
  src/main/kotlin/org/ionproject/integration/job/.gitkeep
  src/main/kotlin/org/ionproject/integration/model/external/.gitkeep
  src/main/kotlin/org/ionproject/integration/model/internal/.gitkeep
  src/main/kotlin/org/ionproject/integration/repository/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/chunkbased/processor/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/chunkbased/reader/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/chunkbased/writer/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/tasklet/.gitkeep
Labels: enhancement

#21 Timetable extraction job architecture
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-job-architecture.md
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-specification.md
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-extraction-architecture.png
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-extraction-flow.png
  docs/batch jobs/isel-timetable-batch-specification.md
Labels: documentation
