Repository i-on-project/integration, pull requests merged in 2020-07, with the labels that each got.

#103 Update timetable/teacher models
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-specification.md
  src/main/kotlin/org/ionproject/integration/builder/implementations/IselTimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/format/implementations/ISELTimetableFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/CourseTeacher.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Event.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/EventCategory.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Language.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Timetable.kt
  src/test/kotlin/org/ionproject/integration/builder/implementations/IselITimetableTeachersBuilderTests.kt
  src/test/kotlin/org/ionproject/integration/format/implementations/ISELTimetableFormatCheckerTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessorTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTaskletTest.kt
Labels: bug

#102 CoreService abstraction and tasklets to upload data
  src/main/kotlin/org/ionproject/integration/job/ISELTimetable.kt
  src/main/kotlin/org/ionproject/integration/model/internal/core/CoreResult.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/UploadType.kt
  src/main/kotlin/org/ionproject/integration/service/implementations/CoreService.kt
  src/main/kotlin/org/ionproject/integration/service/interfaces/ICoreService.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/FacultyTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/TimetableTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/UploadTasklet.kt
  src/main/kotlin/org/ionproject/integration/utils/HttpUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/org/ionproject/integration/IOnIntegrationApplicationTests.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileComparatorImplTest.kt
  src/test/kotlin/org/ionproject/integration/service/implementations/CoreServiceTests.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessorTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/UploadTaskletTests.kt
Labels: enhancement

#107 Refactoring of EmailAlertService and Tests
  src/main/kotlin/org/ionproject/integration/alert/implementations/EmailAlertService.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/writer/AlertOnFailureWriter.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/UploadTasklet.kt
  src/main/kotlin/org/ionproject/integration/utils/EmailUtils.kt
  src/main/kotlin/org/ionproject/integration/utils/JobResult.kt
  src/test/kotlin/org/ionproject/integration/IOnIntegrationApplicationTests.kt
  src/test/kotlin/org/ionproject/integration/alert/implementations/EmailAlertChannelTest.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileComparatorImplTest.kt
  src/test/kotlin/org/ionproject/integration/hash/implementations/HashRepositoryImplTest.kt
  src/test/kotlin/org/ionproject/integration/service/implementations/CoreServiceTests.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/FormatVerifierStepTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessorTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/UploadTaskletTests.kt
  src/test/kotlin/org/ionproject/integration/utils/EmailUtilsTest.kt
  src/test/resources/application.properties
Labels: bug

#104 Bug/upload tasklet
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-specification.md
  src/main/kotlin/org/ionproject/integration/builder/implementations/IselTimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/job/ISELTimetable.kt
  src/main/kotlin/org/ionproject/integration/model/external/.gitkeep
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Course.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/CourseTeacher.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Event.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/EventCategory.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Faculty.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Label.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Language.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/NonRecurrentEvent.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Programme.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/RecurrentEvent.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/School.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Teacher.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Timetable.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/TimetableTeachers.kt
  src/main/kotlin/org/ionproject/integration/model/external/timetable/Weekdays.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Course.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Event.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Faculty.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Label.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Programme.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/School.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Teacher.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/UploadType.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/isel/ProgrammeMap.kt
  src/main/kotlin/org/ionproject/integration/service/implementations/CoreService.kt
  src/main/kotlin/org/ionproject/integration/service/interfaces/ICoreService.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/UploadTasklet.kt
  src/main/resources/config/timetable/isel/isel-leb.properties
  src/main/resources/config/timetable/isel/isel-lec.properties
  src/main/resources/config/timetable/isel/isel-lee.properties
  src/main/resources/config/timetable/isel/isel-leetc.properties
  src/main/resources/config/timetable/isel/isel-leic.properties
  src/main/resources/config/timetable/isel/isel-leim.properties
  src/main/resources/config/timetable/isel/isel-lmate.properties
  src/main/resources/config/timetable/isel/isel-meic.properties
  src/test/kotlin/org/ionproject/integration/builder/implementations/IselITimetableTeachersBuilderTests.kt
  src/test/kotlin/org/ionproject/integration/service/implementations/CoreServiceTests.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/UploadTaskletTests.kt
Labels: bug

#111 Add scheduling
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/writer/GenericCoreWriter.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTasklet.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/writer/GenericCoreWriterTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTaskletTest.kt
  src/test/resources/application.properties
Labels: enhancement

#112 Fix invalid paths
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
Labels: bug

#113 Fix paths
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
Labels: bug

#114 Add Cron expressions
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
Labels: enhancement

#115 Fix Cron
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
Labels: enhancement

#117 Fix windows tests
  src/main/kotlin/org/ionproject/integration/step/chunkbased/reader/ExtractReader.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/FormatVerifierStepTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/GenericParseAndUploadToCoreStepTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTaskletTest.kt
Labels: bug

#118 Update README
  README.md
  img/i-on_logo.png
Labels: enhancement

#121 Update README.md
  README.md
Labels: enhancement

#122 Adds generic batch job documentation
  docs/batch jobs/generic-batch-job/generic-batch-job-architecture-implementation.md
  docs/batch jobs/generic-batch-job/generic-batch-job.png
Labels: documentation

#132 Update documentation
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-specification.md
Labels: bug

#133 Fix invalid config paths
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
Labels: bug

#135 Corrects isel timetable fsm diagram
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-extraction-flow.png
Labels: documentation

#136 Add release badge
  README.md
Labels: enhancement
