Repository i-on-project/integration, pull requests merged in 2020-06, with the labels that each got.

#69 Document base image adoption
  docs/infrastructure/docker-base-image.md
Labels: documentation

#65 Adds DownloadAndCompare Tasklet
  build.gradle.kts
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
  src/main/kotlin/org/ionproject/integration/config/ISELTimetableProperties.kt
  src/main/kotlin/org/ionproject/integration/file/implementations/FileDownloaderImpl.kt
  src/main/kotlin/org/ionproject/integration/file/interfaces/FileDownloader.kt
  src/main/kotlin/org/ionproject/integration/job/.gitkeep
  src/main/kotlin/org/ionproject/integration/job/ISELTimetable.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/exceptions/DownloadAndCompareTaskletException.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTasklet.kt
  src/main/resources/isel-timetable.properties
  src/test/kotlin/org/ionproject/integration/file/PDFFileDownloaderImplTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/utils/SpringBatchTestUtils.kt
  src/test/resources/org/ionproject/integration/step/tasklet/isel-timetable.properties
Labels: enhancement

#66 Implement logic to transform raw data to business data
  build.gradle.kts
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-specification.md
  src/main/kotlin/org/ionproject/integration/builder/exceptions/TimetableTeachersBuilderException.kt
  src/main/kotlin/org/ionproject/integration/builder/implementations/IselTimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/builder/interfaces/TimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/format/implementations/ISELTimetableFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/model/internal/iseltimetable/DynamicObject.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Course.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/CourseTeacher.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Event.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Faculty.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Label.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Programme.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/School.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Teacher.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Timetable.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/TimetableTeachers.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/Weekdays.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/isel/RawData.kt
  src/main/kotlin/org/ionproject/integration/utils/JsonUtils.kt
  src/main/kotlin/org/ionproject/integration/utils/RegexUtils.kt
  src/test/kotlin/org/ionproject/integration/builder/implementations/IselTimetableTeachersBuilderTests.kt
  src/test/kotlin/org/ionproject/integration/format/implementations/ISELTimetableFormatCheckerTest.kt
  src/test/kotlin/org/ionproject/integration/utils/JsonUtilsTests.kt
  src/test/kotlin/org/ionproject/integration/utils/RegexUtilsTests.kt
Labels: enhancement

#76 Adds FileComparator
  src/main/kotlin/org/ionproject/integration/file/implementations/FileComparatorImpl.kt
  src/main/kotlin/org/ionproject/integration/file/implementations/FileDigestImpl.kt
  src/main/kotlin/org/ionproject/integration/file/interfaces/FileComparator.kt
  src/main/kotlin/org/ionproject/integration/file/interfaces/FileDigest.kt
  src/main/kotlin/org/ionproject/integration/hash/.gitkeep
  src/main/kotlin/org/ionproject/integration/hash/implementations/HashRepositoryImpl.kt
  src/main/kotlin/org/ionproject/integration/hash/interfaces/HashRepository.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileComparatorImplTest.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileDigestImplTest.kt
  src/test/kotlin/org/ionproject/integration/hash/implementations/HashRepositoryImplTest.kt
  src/test/resources/application.properties
  src/test/resources/org/ionproject/integration/file/implementations/insert-file-comparator-job.sql
  src/test/resources/org/ionproject/integration/file/implementations/insert-hash-not-same.sql
  src/test/resources/org/ionproject/integration/hash/implementations/insert-test-job.sql
  src/test/resources/org/ionproject/integration/hash/implementations/insert-yet-another-job.sql
  src/test/resources/tests-schema.sql
Labels: enhancement

#67 Investigate how to pass configuration for batch jobs
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-configuration-file-specification.md
  docs/batch jobs/configuration/batch-job-configuration.md
Labels: documentation

#73 Adds Timetable Job complete definition
  build.gradle.kts
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
  src/main/kotlin/org/ionproject/integration/builder/implementations/IselTimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/config/ISELTimetableProperties.kt
  src/main/kotlin/org/ionproject/integration/format/implementations/ISELTimetableFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/format/interfaces/RawDataFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/job/ISELTimetable.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/FormatVerifierStepBuilder.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/processor/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessor.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/reader/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/chunkbased/reader/ExtractReader.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/writer/.gitkeep
  src/main/kotlin/org/ionproject/integration/step/chunkbased/writer/AlertOnFailureWriter.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/FacultyTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/TimetableTasklet.kt
  src/main/kotlin/org/ionproject/integration/utils/JsonUtils.kt
  src/main/resources/application.properties
  src/main/resources/config/timetable/isel/isel-leic.properties
  src/main/resources/config/timetable/isel/isel-meic.properties
  src/main/resources/isel-timetable.properties
  src/test/kotlin/org/ionproject/integration/step/chunkbased/FormatVerifierStepTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessorTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/writer/AlertOnFailureWriterTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/utils/SpringBatchTestUtils.kt
  src/test/resources/formatTest.pdf
  src/test/resources/org/ionproject/integration/step/tasklet/isel-timetable.properties
Labels: enhancement

#75 Deploy to Google Cloud
  .github/workflows/IOnIntegration_Production.yml
  .github/workflows/IOnIntegration_Staging.yml
  build.gradle.kts
Labels: enhancement

#79 Gcloud password needs to be escaped
  .github/workflows/IOnIntegration_Production.yml
  .github/workflows/IOnIntegration_Staging.yml
Labels: bug

#80 Fix setup gcloud cli
  .github/workflows/IOnIntegration_Production.yml
  .github/workflows/IOnIntegration_Staging.yml
Labels: bug

#81 Revert fix reference
  .github/workflows/IOnIntegration_Production.yml
  .github/workflows/IOnIntegration_Staging.yml
Labels: bug

#82 Refactor env variable access
  build.gradle.kts
Labels: bug

#83 Revert fix; Correct cmd task deploy
  build.gradle.kts
Labels: bug

#84 Add zone param to deploy cmd
  build.gradle.kts
Labels: bug

#86 Corrected tests for windows environment
  src/main/kotlin/org/ionproject/integration/step/chunkbased/reader/ExtractReader.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileComparatorImplTest.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileDigestImplTest.kt
  src/test/kotlin/org/ionproject/integration/utils/TryTests.kt
Labels: bug

#71 Application.properties per environment
  Dockerfile
  build.gradle.kts
  src/main/kotlin/org/ionproject/integration/config/AppProperties.kt
  src/main/resources/application.properties
  src/test/kotlin/org/ionproject/integration/IOnIntegrationApplicationTests.kt
  src/test/kotlin/org/ionproject/integration/extractor/implementations/ITextPdfExtractorTests.kt
  src/test/kotlin/org/ionproject/integration/extractor/implementations/TabulaPdfExtractorTests.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileComparatorImplTest.kt
  src/test/kotlin/org/ionproject/integration/hash/implementations/HashRepositoryImplTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/FormatVerifierStepTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessorTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/writer/AlertOnFailureWriterTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTaskletTest.kt
Labels: enhancement

#87 Adds support for recording and retrieving pdf document hash in isel timetable job
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
  src/main/kotlin/org/ionproject/integration/file/implementations/FileComparatorImpl.kt
  src/main/kotlin/org/ionproject/integration/job/ISELTimetable.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/reader/ExtractReader.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTasklet.kt
  src/main/resources/schema-postgresql.sql
  src/test/kotlin/org/ionproject/integration/step/chunkbased/FormatVerifierStepTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/utils/SpringBatchTestUtils.kt
  src/test/resources/org/ionproject/integration/step/tasklet/iseltimetable/implementations/insert-hash-post-upload-test.sql
  src/test/resources/org/ionproject/integration/step/tasklet/iseltimetable/implementations/insert-timetable-pdf-hash.sql
  src/test/resources/tests-schema.sql
Labels: enhancement

#90 Demo related issues
  Dockerfile
  src/main/kotlin/org/ionproject/integration/IOnIntegrationApplication.kt
  src/main/resources/application.properties
  src/main/resources/config/timetable/isel/isel-leic.properties
  src/main/resources/config/timetable/isel/isel-meic.properties
Labels: enhancement

#91 Add datasource initialization mode
  src/main/resources/application.properties
Labels: bug

#92 Missing '=' on gcloud deploy command
  build.gradle.kts
Labels: bug

#97 Refactoring
  docs/batch jobs/ISEL timetable extraction batch job/isel-timetable-batch-configuration-file-specification.md
  src/main/kotlin/org/ionproject/integration/builder/implementations/IselTimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/builder/interfaces/ITimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/config/AppProperties.kt
  src/main/kotlin/org/ionproject/integration/extractor/implementations/ITextPdfExtractor.kt
  src/main/kotlin/org/ionproject/integration/extractor/implementations/TabulaPdfExtractor.kt
  src/main/kotlin/org/ionproject/integration/extractor/interfaces/IPdfExtractor.kt
  src/main/kotlin/org/ionproject/integration/file/implementations/FileComparatorImpl.kt
  src/main/kotlin/org/ionproject/integration/file/implementations/FileDigestImpl.kt
  src/main/kotlin/org/ionproject/integration/file/implementations/FileDownloaderImpl.kt
  src/main/kotlin/org/ionproject/integration/file/implementations/PDFBytesFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/file/interfaces/IBytesFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/file/interfaces/IFileComparator.kt
  src/main/kotlin/org/ionproject/integration/file/interfaces/IFileDigest.kt
  src/main/kotlin/org/ionproject/integration/file/interfaces/IFileDownloader.kt
  src/main/kotlin/org/ionproject/integration/format/implementations/ISELTimetableFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/format/implementations/JsonFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/format/implementations/StringFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/format/interfaces/IFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/format/interfaces/IRawDataFormatChecker.kt
  src/main/kotlin/org/ionproject/integration/hash/implementations/HashRepositoryImpl.kt
  src/main/kotlin/org/ionproject/integration/hash/interfaces/IHashRepository.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessor.kt
  src/main/kotlin/org/ionproject/integration/step/chunkbased/reader/ExtractReader.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTasklet.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTasklet.kt
  src/main/resources/application.properties
  src/main/resources/config/timetable/isel/isel-leic.properties
  src/main/resources/config/timetable/isel/isel-meic.properties
  src/test/kotlin/org/ionproject/integration/IOnIntegrationApplicationTests.kt
  src/test/kotlin/org/ionproject/integration/builder/implementations/IselITimetableTeachersBuilderTests.kt
  src/test/kotlin/org/ionproject/integration/file/PDFFileDownloaderImplTest.kt
  src/test/kotlin/org/ionproject/integration/file/implementations/FileComparatorImplTest.kt
  src/test/kotlin/org/ionproject/integration/hash/implementations/HashRepositoryImplTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/FormatVerifierStepTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/processor/FormatVerifierProcessorTest.kt
  src/test/kotlin/org/ionproject/integration/step/chunkbased/writer/AlertOnFailureWriterTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/DownloadAndCompareTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/MappingTaskletTest.kt
  src/test/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/PostUploadTaskletTest.kt
Labels: enhancement
