Repository i-on-project/integration, pull requests merged in 2021-05, with the labels that each got.

#180 Added sub-project FileRepository to Spring Project
  app/build.gradle.kts
  build.gradle.kts
  file-repository/build.gradle.kts
  file-repository/src/main/kotlin/org/ionproject/integration/filerepository/StubFileRepository.kt
  gradle.properties
  settings.gradle.kts
Labels: enhancement

#198 From DTO to Git 🚀
  src/main/kotlin/org/ionproject/integration/job/ISELTimetable.kt
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/WriteFileTasklet.kt
Labels: enhancement

#206 add branch env variable
  .env
  docker-compose.yml
  src/main/kotlin/org/ionproject/integration/config/AppProperties.kt
  src/main/kotlin/org/ionproject/integration/dispatcher/DispatcherImpl.kt
  src/main/kotlin/org/ionproject/integration/dispatcher/git/GitHandlerImpl.kt
  src/main/kotlin/org/ionproject/integration/dispatcher/git/IGitHandler.kt
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: enhancement

#205 Added env variables in Staging workflow
  .github/workflows/IOnIntegration_Staging.yml
  .gitignore
Labels: enhancement

#210 Bug deploy staging
  .github/workflows/IOnIntegration_Staging.yml
Labels: bug

#212 changed docker_heroku_process_type to worker and added masks
  .github/workflows/IOnIntegration_Staging.yml
Labels: bug

#214 add jvm flag for optimized container support in Dockerfile
  src/main/kotlin/org/ionproject/integration/file/implementations/FileDownloaderImpl.kt
Labels: bug

#216 make git handler a singleton to avoid duplicate checkouts
  src/main/kotlin/org/ionproject/integration/dispatcher/git/GitHandlerImpl.kt
Labels: bug

#218 Add support for remaining ADEETC courses
  src/main/kotlin/org/ionproject/integration/builder/implementations/IselTimetableTeachersBuilder.kt
  src/main/kotlin/org/ionproject/integration/model/internal/timetable/isel/ProgrammeMap.kt
  src/main/kotlin/org/ionproject/integration/utils/StringUtils.kt
  src/main/resources/config/timetable/isel/isel-leirt.properties
  src/main/resources/config/timetable/isel/isel-meim.properties
  src/test/kotlin/org/ionproject/integration/utils/StringUtilsTest.kt
Labels: enhancement

#221 Dispatcher test
  build.gradle.kts
  src/main/kotlin/org/ionproject/integration/dispatcher/DispatcherImpl.kt
  src/test/kotlin/org/ionproject/integration/dispatcher/DispatcherTests.kt
Labels: enhancement

#223 document how to write to Github
  README.md
Labels: documentation

#227 Update README.md
  README.md
Labels: documentation

#229 fix institution identifier
  src/main/kotlin/org/ionproject/integration/step/tasklet/iseltimetable/implementations/WriteFileTasklet.kt
  src/main/kotlin/org/ionproject/integration/utils/StringUtils.kt
Labels: bug
