Repository i-on-project/integration, pull requests merged in 2021-07, with the labels that each got.

#280 Update production pipeline to deploy to GHCR
  .github/workflows/IOnIntegration_Production.yml
Labels: enhancement

#282 Update README.md
  README.md
Labels: documentation

#298 small UI layer package restructuring
  src/main/kotlin/org/ionproject/integration/ui/controller/ControllerConfig.kt
  src/main/kotlin/org/ionproject/integration/ui/controller/JobController.kt
  src/main/kotlin/org/ionproject/integration/ui/input/CreateJobDto.kt
  src/main/kotlin/org/ionproject/integration/ui/input/InputProcessor.kt
  src/main/kotlin/org/ionproject/integration/ui/input/SafeCalendarJobDto.kt
  src/main/kotlin/org/ionproject/integration/ui/input/SafeEvaluationsJobDto.kt
  src/main/kotlin/org/ionproject/integration/ui/input/SafeJobDto.kt
  src/main/kotlin/org/ionproject/integration/ui/input/SafeTimetableJobDto.kt
  src/main/kotlin/org/ionproject/integration/ui/output/JobDetailDto.kt
  src/main/kotlin/org/ionproject/integration/ui/output/PostResponse.kt
  src/main/kotlin/org/ionproject/integration/ui/output/Problem.kt
  src/test/kotlin/org/ionproject/integration/ui/controller/JobControllerTests.kt
  src/test/kotlin/org/ionproject/integration/ui/dto/InputProcessorTests.kt
Labels: enhancement

#303 Staging script improvement
  .github/workflows/IOnIntegration_Staging.yml
Labels: bug

#306 delete file if it already exists
  src/main/kotlin/org/ionproject/integration/application/job/tasklet/DownloadAndCompareTasklet.kt
Labels: bug

#308 normalize section DTOs to remove duplicate sections
  src/main/kotlin/org/ionproject/integration/domain/timetable/dto/OutputRepresentations.kt
Labels: bug

#311 add auth data to swagger ui
  src/main/kotlin/org/ionproject/integration/ui/controller/JobController.kt
Labels: enhancement

#310 correction in evaluation business object construction
  src/main/kotlin/org/ionproject/integration/domain/evaluations/BusinessObjects.kt
  src/test/kotlin/org/ionproject/integration/domain/evaluations/EvaluationsBusinessObjFormatCheckerTest.kt
Labels: enhancement

#312 Update README.md
  README.md
Labels: documentation
